import { InstitutionalEvidenceInput, InstitutionalOutcomeRecord } from './institutional-outcomes-types';

export function mapReportToInstitutionalEvidenceInput(
  existingRecords: any[],
  executiveSovereigntyReport: any
): InstitutionalEvidenceInput {
  
  const records: InstitutionalOutcomeRecord[] = [...(existingRecords || [])];
  
  // Extract E1 (Insights) and E2 (Recommendations) natively generated by the pipeline
  if (executiveSovereigntyReport) {
    
    // Extract E1 from Sector Intelligence
    if (executiveSovereigntyReport.sectorIntelligence?.capabilityGaps?.length) {
      executiveSovereigntyReport.sectorIntelligence.capabilityGaps.forEach((gap: string, idx: number) => {
        records.push({
          id: `sys-insight-gap-${Date.now()}-${idx}`,
          category: 'STRATEGY',
          level: 'E1',
          source: 'SYSTEM_RUNTIME',
          sourceReference: 'SectorIntelligenceLayer',
          description: `Identified capability gap: ${gap}`,
          dateLogged: new Date().toISOString()
        });
      });
    }

    // Extract E2 from Capital Allocation Intelligence
    if (executiveSovereigntyReport.capitalAllocationIntelligence?.strategicInvestmentPriorities?.length) {
      executiveSovereigntyReport.capitalAllocationIntelligence.strategicInvestmentPriorities.forEach((priority: any, idx: number) => {
        records.push({
          id: `sys-rec-priority-${Date.now()}-${idx}`,
          category: 'CAPITAL_ALLOCATION',
          level: 'E2',
          source: 'SYSTEM_RUNTIME',
          sourceReference: 'CapitalAllocationIntelligenceLayer',
          description: `Recommended strategic priority: ${priority.priority || priority}`,
          dateLogged: new Date().toISOString()
        });
      });
    }

    // Extract E1 from Governance Digital Twin
    if (executiveSovereigntyReport.governanceDigitalTwin?.executionCapacity?.classification) {
      records.push({
        id: `sys-insight-exec-${Date.now()}`,
        category: 'EXECUTION',
        level: 'E1',
        source: 'SYSTEM_RUNTIME',
        sourceReference: 'GovernanceDigitalTwin',
        description: `Execution capacity classified as ${executiveSovereigntyReport.governanceDigitalTwin.executionCapacity.classification}`,
        dateLogged: new Date().toISOString()
      });
    }
  }

  return {
    existingRecords: records,
    executiveSovereigntyReport
  };
}
