export class FiduciaryNarrativeViolation extends Error {
  public metadata: {
    bannedTerm: string;
    textSample: string;
  };

  constructor(message: string, bannedTerm: string, textSample: string) {
    super(message);
    this.name = 'FiduciaryNarrativeViolation';
    this.metadata = { bannedTerm, textSample };
    Object.setPrototypeOf(this, FiduciaryNarrativeViolation.prototype);
  }
}

export class ExecutiveNarrativeSanitizer {
  private static BANNED_PATTERNS = [
    { regex: /\bcausou\b/i, term: 'causou' },
    { regex: /\bprovou\b/i, term: 'provou' },
    { regex: /demonstrou\s+definitivamente/i, term: 'demonstrou definitivamente' },
    { regex: /inevitavelmente\s+levar[aá]/i, term: 'inevitavelmente levará' },
    { regex: /evid[eê]ncia\s+falha/i, term: 'evidencia falha' },
    { regex: /resultar[aá]\s+em/i, term: 'resultará em' },
    { regex: /respons[aá]vel\s+pela\s+deterioraç[aã]o/i, term: 'responsável pela deterioração' },
    { regex: /determinou\s+o\s+colapso/i, term: 'determinou o colapso' },
    { regex: /explica\s+completamente/i, term: 'explica completamente' },
    { regex: /gest[aã]o\s+falhou/i, term: 'gestão falhou' },
    { regex: /mal\s+administrada/i, term: 'mal administrada' },
    { regex: /resist[eê]ncia\s+interna/i, term: 'resistência interna' },
    { regex: /baixa\s+maturidade/i, term: 'baixa maturidade' },
    { regex: /incompet[eê]ncia/i, term: 'incompetência' }
  ];

  private static TECHNICAL_LEAKS = [
    { regex: /\bInfinity\b/g, replacement: 'Valor não aplicável' },
    { regex: /\bNaN\b/g, replacement: 'Dados insuficientes' },
    { regex: /\bUndefined\b/gi, replacement: 'Não identificado' },
    { regex: /\bNull\b/gi, replacement: 'Não identificado' },
    { regex: /DISCLOSURE_[A-Z_]+/g, replacement: 'Parâmetros de divulgação omitidos' },
    { regex: /RUNTIME_[A-Z_]+/g, replacement: 'Condições operacionais de sistema' },
    { regex: /ENGINE_[A-Z_]+/g, replacement: 'Diagnóstico analítico interno' },
    { regex: /SOVEREIGN_[A-Z_]+/g, replacement: 'Diretrizes de governança aplicadas' },
    { regex: /\[INSUFFICIENT_DATA\]/g, replacement: '' },
    { regex: /\[NOT_APPLICABLE\]/g, replacement: '' }
  ];

  public static sanitize(text: string): string {
    if (!text) return '';

    let sanitized = text;

    // 1. Block Fiduciary Violations (Throws)
    for (const pattern of this.BANNED_PATTERNS) {
      if (pattern.regex.test(sanitized)) {
        throw new FiduciaryNarrativeViolation(
          `Violação de linguagem fiduciária: Termo proibido '${pattern.term}' detectado na narrativa.`,
          pattern.term,
          sanitized
        );
      }
    }

    // 2. Filter Technical Leaks (Replaces)
    for (const leak of this.TECHNICAL_LEAKS) {
      sanitized = sanitized.replace(leak.regex, leak.replacement);
    }

    // Cleanup multiple spaces generated by replacements
    sanitized = sanitized.replace(/\s{2,}/g, ' ').trim();

    return sanitized;
  }
}
