// src/lib/executive-financial-story-mapper.ts
import type { ExecutiveFinancialStoryInput, ExecutiveFinancialStoryReportLike } from './executive-financial-story-types';

/**
 * Maps a report‑like object (generated by UFNE or a subset) to the EFSL input.
 * Returns an object with the optional fields populated when present.
 */
export function mapReportToExecutiveFinancialStoryInput(report: ExecutiveFinancialStoryReportLike): ExecutiveFinancialStoryInput {
  return {
    narrativeContext: report.narrativeContext,
    unifiedFinancialNarrative: report.unifiedFinancialNarrative,
  };
}
