export type LifecycleFallbackReason = 
  | 'MISSING_CLIENT'
  | 'MISSING_FOUNDATION_YEAR'
  | 'LIFECYCLE_CONTEXT_NOT_BUILT'
  | 'LIFECYCLE_PROFILE_NOT_BUILT'
  | 'RUNTIME_CONTEXT_MISSING_LIFECYCLE'
  | 'ADAPTER_DID_NOT_RECEIVE_PROFILE'
  | 'DLPA_ENGINE_DID_NOT_RECEIVE_PROFILE'
  | 'UI_DID_NOT_RECEIVE_PROFILE'
  | 'UNKNOWN';

export const LifecycleFallbackReasons = {
  MISSING_CLIENT: 'MISSING_CLIENT' as LifecycleFallbackReason,
  MISSING_FOUNDATION_YEAR: 'MISSING_FOUNDATION_YEAR' as LifecycleFallbackReason,
  LIFECYCLE_CONTEXT_NOT_BUILT: 'LIFECYCLE_CONTEXT_NOT_BUILT' as LifecycleFallbackReason,
  LIFECYCLE_PROFILE_NOT_BUILT: 'LIFECYCLE_PROFILE_NOT_BUILT' as LifecycleFallbackReason,
  RUNTIME_CONTEXT_MISSING_LIFECYCLE: 'RUNTIME_CONTEXT_MISSING_LIFECYCLE' as LifecycleFallbackReason,
  ADAPTER_DID_NOT_RECEIVE_PROFILE: 'ADAPTER_DID_NOT_RECEIVE_PROFILE' as LifecycleFallbackReason,
  DLPA_ENGINE_DID_NOT_RECEIVE_PROFILE: 'DLPA_ENGINE_DID_NOT_RECEIVE_PROFILE' as LifecycleFallbackReason,
  UI_DID_NOT_RECEIVE_PROFILE: 'UI_DID_NOT_RECEIVE_PROFILE' as LifecycleFallbackReason,
  UNKNOWN: 'UNKNOWN' as LifecycleFallbackReason,
};
