export enum ExecutiveOffice {
  CFO_OFFICE = 'CFO_OFFICE',
  BOARD_INTELLIGENCE = 'BOARD_GOVERNANCE',
  CEO_OFFICE = 'CEO_OFFICE',
  COO_OFFICE = 'COO_OFFICE',
  COMMERCIAL_OFFICE = 'COMMERCIAL_OFFICE'
}
