export const DOCUMENT_TYPES = [
  'Balanço Patrimonial',
  'DRE',
  'DRE Gerencial',
  'DLPA',
  'DFC',
  'Contas a Pagar',
  'Contas a Receber',
  'Folha de Pagamento',
  'Vendas / Comercial',
  'Compras / Suprimentos',
  'Ativos Financeiros',
  'Passivos / Empréstimos',
  'Orçamento / Budget',
  'Plano de Contas',
  'OKRs / Metas',
  'Diretrizes Estratégicas',
  'Diagnóstico IVE',
  'Marketing / Branding',
  'Produção / Operações',
  'Logística / Supply Chain',
  'RH / People',
  'TI / Infraestrutura',
  'Jurídico / Compliance'
];
