export enum DecisionStatus {
  EXPLORING = 'EXPLORING',
  UNDER_REVIEW = 'UNDER_REVIEW',
  APPROVED_BY_HUMAN = 'APPROVED_BY_HUMAN',
  EXECUTING = 'EXECUTING',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED'
}
