export enum ExperienceSectionOrder {
  EXECUTIVE_SUMMARY = 1,
  STRATEGIC_INTERPRETATION = 2,
  INTELLIGENCE_DOMAINS = 3,
  CFO_QUESTIONS = 5,
  
  // Wave 1.4.8 Strict CFO Office Layers
  EXECUTIVE_FINANCIAL_OVERVIEW = 10,
  FINANCIAL_DIAGNOSIS = 20,
  INTELLIGENCE_SIGNALS = 30,
  HISTORICAL_EVOLUTION = 40,
  EXECUTIVE_QUESTIONS = 50,
  
  // Absolute last section
  TECHNICAL_EVIDENCE = 100
}
