export enum LeadSource {
  INBOUND = 'INBOUND',
  OUTBOUND = 'OUTBOUND',
  CERTIFIED_ADVISOR = 'CERTIFIED_ADVISOR',
  EXECUTIVE_PARTNER = 'EXECUTIVE_PARTNER',
  REFERRAL = 'REFERRAL',
  EVENT = 'EVENT',
  MARKETING = 'MARKETING',
  API = 'API',
  INTERNAL_EXECUTIVE = 'INTERNAL_EXECUTIVE'
}
