export enum DecisionStatus {
  PENDING = 'PENDING',
  CLARIFICATION_REQUESTED = 'CLARIFICATION_REQUESTED',
  ADJUSTMENT_REQUESTED = 'ADJUSTMENT_REQUESTED',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED'
}

export enum DecisionActionType {
  REQUEST_MEETING = 'REQUEST_MEETING',
  REQUEST_ADJUSTMENT = 'REQUEST_ADJUSTMENT',
  ACCEPT = 'ACCEPT',
  REJECT = 'REJECT'
}
