// src/core/runtime/institutional-recovery/FalseRecoveryDetectionEngine.ts

import { RecoveryEvaluationInput } from './RecoveryTypes';

export interface FalseRecoveryResult {
  falseRecoveryDetected: boolean;
  falseRecoveryDrivers: string[];
}

export class FalseRecoveryDetectionEngine {
  public static detect(input: RecoveryEvaluationInput): FalseRecoveryResult {
    const fco = input.fco ?? 0;
    const netIncome = input.netIncome ?? 0;
    const availableCash = input.availableCash ?? 0;
    const historicalCycles = input.historicalCycles || [];
    const memoryProfile = input.memoryProfile || {};
    const fiduciaryOutput = input.fiduciaryOutput || {};
    
    const falseRecoveryDrivers: string[] = [];

    // 1. Profit generated by non-operational events (Lucro isolado sem FCO)
    if (netIncome > 0 && fco <= 0) {
      falseRecoveryDrivers.push('LUCRO_SEM_CONVERSAO_DE_CAIXA_OPERACIONAL');
    }

    // 2. Caixa temporário sem geração operacional
    // We assume if cash is high or increased but fco is negative
    if (availableCash > 0 && fco <= 0 && (memoryProfile?.cashInjections || input.treasuryRuntime?.hasNewDebt)) {
      falseRecoveryDrivers.push('CAIXA_ARTIFICIAL_POR_APORTE_OU_DIVIDA_SEM_FCO');
    }

    // 3. Recuperação com preservação patrimonial insuficiente
    if (fiduciaryOutput.patrimonialIntegrityStatus && fiduciaryOutput.patrimonialIntegrityStatus !== 'PRESERVED') {
      falseRecoveryDrivers.push('RECUPERACAO_COM_EROSAO_PATRIMONIAL_ATIVA');
    }

    // 4. Histórico de retenção forçada nos últimos 2 ciclos
    let recentForcedRetention = fiduciaryOutput.retentionClassification === 'FORCED_RETENTION' || fiduciaryOutput.retentionClassification === 'EMERGENCY_RETENTION';
    if (!recentForcedRetention && historicalCycles.length > 0) {
      for (let i = 0; i < Math.min(2, historicalCycles.length); i++) {
        if (historicalCycles[i].retentionClassification === 'FORCED_RETENTION' || historicalCycles[i].retentionClassification === 'EMERGENCY_RETENTION') {
          recentForcedRetention = true;
          break;
        }
      }
    }
    
    // We might not fail completely just for history, but if FCO is positive and we still have pressured equity, it's false recovery
    if (recentForcedRetention && fco <= 0) {
      falseRecoveryDrivers.push('RETENCAO_FORCADA_RECENTE_SEM_VIRADA_OPERACIONAL');
    }

    // 5. EBITDA sem FCO
    if (memoryProfile?.ebitdaImproved && fco <= 0) {
      falseRecoveryDrivers.push('MELHORA_EBITDA_SEM_CONVERSAO_EM_CAIXA');
    }

    const falseRecoveryDetected = falseRecoveryDrivers.length > 0;

    return {
      falseRecoveryDetected,
      falseRecoveryDrivers
    };
  }
}
