export enum EIMIDimension {
  CONTEXT_INTELLIGENCE = 'CONTEXT_INTELLIGENCE',
  DECISION_GOVERNANCE = 'DECISION_GOVERNANCE',
  RISK_ANTICIPATION = 'RISK_ANTICIPATION',
  INSTITUTIONAL_MEMORY = 'INSTITUTIONAL_MEMORY',
  EXECUTION_INTELLIGENCE = 'EXECUTION_INTELLIGENCE',
  ADAPTIVE_CAPACITY = 'ADAPTIVE_CAPACITY',
  FIDUCIARY_TRACEABILITY = 'FIDUCIARY_TRACEABILITY'
}

export interface DimensionScore {
  dimension: EIMIDimension;
  score: number; // 0.0 to 10.0
  evidenceCount: number;
}
