// re-export shim — movido para src/workspace/runtime/executive-consolidation/
export * from '../../../workspace/runtime/executive-consolidation/AssetQualityExecutiveAssessmentEngine';
export * from '../../../workspace/runtime/executive-consolidation/BADIConsistencyEngine';
export * from '../../../workspace/runtime/executive-consolidation/BalanceSheetCompletenessGuard';
export * from '../../../workspace/runtime/executive-consolidation/BalanceSheetDecisionPolicyLayer';
export * from '../../../workspace/runtime/executive-consolidation/BalanceSheetDiagnosticEngine';
export * from '../../../workspace/runtime/executive-consolidation/BalanceSheetExecutiveFactsBuilder';
export * from '../../../workspace/runtime/executive-consolidation/BalanceSheetExecutiveLanguageCompiler';
export * from '../../../workspace/runtime/executive-consolidation/BalanceSheetExecutiveViewModelBuilder';
export * from '../../../workspace/runtime/executive-consolidation/BalanceSheetScenarioClassifier';
export * from '../../../workspace/runtime/executive-consolidation/BalanceSheetTechnicalIndicatorRegistry';
export * from '../../../workspace/runtime/executive-consolidation/BoardDecisionEscalationEngine';
export * from '../../../workspace/runtime/executive-consolidation/CanonicalDivergenceAuditEngine';
export * from '../../../workspace/runtime/executive-consolidation/CapitalEfficiencyExecutiveAssessmentEngine';
export * from '../../../workspace/runtime/executive-consolidation/CapitalEfficiencyMetricsProvider';
export * from '../../../workspace/runtime/executive-consolidation/CapitalEfficiencyRuleSet';
export * from '../../../workspace/runtime/executive-consolidation/CapitalPreservationExecutiveAssessmentEngine';
export * from '../../../workspace/runtime/executive-consolidation/CapitalProtectionCanonicalResolver';
export * from '../../../workspace/runtime/executive-consolidation/CapitalStructureExecutiveAssessmentEngine';
export * from '../../../workspace/runtime/executive-consolidation/CompositeScoreGovernanceEngine';
export * from '../../../workspace/runtime/executive-consolidation/CrossStatementBindingResolver';
export * from '../../../workspace/runtime/executive-consolidation/CrossStatementExecutiveNarrativeEngine';
export * from '../../../workspace/runtime/executive-consolidation/CrossStatementPresentationGuard';
export * from '../../../workspace/runtime/executive-consolidation/CrossStatementPropagationEngine';
export * from '../../../workspace/runtime/executive-consolidation/EFOSExecutiveConsistencyAuditEngine';
// sanitize de EFOS tem assinatura diferente de ExecutiveSemanticBoundaryGuard — exportar com alias para evitar TS2308
export { sanitize as sanitizeEfosLabel } from '../../../workspace/runtime/executive-consolidation/EFOSExecutiveLanguageBoundaryGuard';
export * from '../../../workspace/runtime/executive-consolidation/EFOSPresentationLeakGuard';
export * from '../../../workspace/runtime/executive-consolidation/EvidenceHeuristicsRegistry';
export * from '../../../workspace/runtime/executive-consolidation/EvidenceSelector';
export * from '../../../workspace/runtime/executive-consolidation/ExecutiveActionCompletenessAudit';
export * from '../../../workspace/runtime/executive-consolidation/ExecutiveBlockedAnalysisTranslator';
export * from '../../../workspace/runtime/executive-consolidation/ExecutiveBusinessTerminologyRegistry';
// export * from '../../../workspace/runtime/executive-consolidation/ExecutiveConsistencyEngine';
  // TS2308: duplicate exportexport * from '../../../workspace/runtime/executive-consolidation/ExecutiveDecisionSynthesisEngine';
export * from '../../../workspace/runtime/executive-consolidation/ExecutiveDriverCatalog';
export * from '../../../workspace/runtime/executive-consolidation/ExecutiveDriverQualifiers';
export * from '../../../workspace/runtime/executive-consolidation/ExecutiveIndicatorExplanationEngine';
export * from '../../../workspace/runtime/executive-consolidation/ExecutiveNarrativeBuilder';
export * from '../../../workspace/runtime/executive-consolidation/ExecutiveNarrativeSanitizer';
export * from '../../../workspace/runtime/executive-consolidation/ExecutiveNarrativeVariations';
export * from '../../../workspace/runtime/executive-consolidation/ExecutivePrimaryMotiveConsistencyEngine';
export * from '../../../workspace/runtime/executive-consolidation/ExecutiveRecommendationDeduplicationEngine';
export * from '../../../workspace/runtime/executive-consolidation/ExecutiveSemanticAudit';
export { sanitize, translate, validate } from '../../../workspace/runtime/executive-consolidation/ExecutiveSemanticBoundaryGuard';
  // TS2308: duplicate exportexport * from '../../../workspace/runtime/executive-consolidation/ExecutiveSemanticRegistry';
export * from '../../../workspace/runtime/executive-consolidation/ExecutiveStrategicMaturityEngine';
export * from '../../../workspace/runtime/executive-consolidation/ExecutiveStrategicSnapshotEngine';
export * from '../../../workspace/runtime/executive-consolidation/ExecutiveStrategicTensionEngine';
export * from '../../../workspace/runtime/executive-consolidation/ExecutiveSynthesisTypes';
export * from '../../../workspace/runtime/executive-consolidation/HistoricalInsightEngine';
export * from '../../../workspace/runtime/executive-consolidation/LiquidityExecutiveAssessmentEngine';
export * from '../../../workspace/runtime/executive-consolidation/MetricCanonicalizationEngine';
export * from '../../../workspace/runtime/executive-consolidation/NumericIntegrityGuard';
export * from '../../../workspace/runtime/executive-consolidation/ProductionVisibilityPolicy';
export * from '../../../workspace/runtime/executive-consolidation/Resolvers';
export * from '../../../workspace/runtime/executive-consolidation/RuntimeLineageGuard';
export * from '../../../workspace/runtime/executive-consolidation/StrategicDiagnosisStageResolver';
// AnalyticalModule conflita com ExecutiveDriverCatalog — exportar nomes específicos
export { StrategicOpinionConsistencyEngine } from '../../../workspace/runtime/executive-consolidation/StrategicOpinionConsistencyEngine';
export type { ExecutiveAnalysisContext, StrategicSeverityLevel, StrategicOpinion } from '../../../workspace/runtime/executive-consolidation/StrategicOpinionConsistencyEngine';
  // TS2308: duplicate exportexport * from '../../../workspace/runtime/executive-consolidation/SynthesisMetricsResolver';
export * from '../../../workspace/runtime/executive-consolidation/WorkingCapitalExecutiveAssessmentEngine';
