import { Contract, ContractStatus, ContractTerms, ContractOrigin } from '@domain/contract';

interface CreateContractCommand {
  customerId: string;
  proposalReference?: string;
  acceptanceReference?: string;
  terms: {
    planId: string;
    startDate: string;
    currency: string;
    billingCycle: string;
  };
}

export class CreateContractUseCase {
  /**
   * Orchestrates the creation of a Contract from an Executive Decision.
   * This use case receives DTOs/Commands, translates them into Domain Value Objects,
   * instantiates the Aggregate Root, and would typically save it via a Repository.
   */
  public execute(command: CreateContractCommand): Contract {
    // 1. Map to Value Objects
    const origin: ContractOrigin = {
      proposalReference: command.proposalReference,
      acceptanceReference: command.acceptanceReference,
    };

    const terms: ContractTerms = {
      planId: command.terms.planId,
      period: { startDate: command.terms.startDate },
      currency: command.terms.currency,
      billingCycle: command.terms.billingCycle,
    };

    // 2. Instantiate Aggregate
    const contract: Contract = {
      id: `CTR-${Date.now()}`, // Typically generated by a sequence or UUID
      version: 1,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      customer: command.customerId,
      origin,
      terms,
      status: ContractStatus.DRAFT,
      lifecycle: {},
    };

    // 3. (In real implementation) Save via ContractRepository
    // 4. (In real implementation) Dispatch Domain Event (ContractCreated)

    return contract;
  }
}
