export const ConstitutionalSemanticAuthorityRegistry = {
  APPROVED_AUTHORITIES: ['ELSA'],
  APPROVED_SOURCES: ['ELSA', 'AUDIT', 'TECHNICAL_INTERNAL'],
  FORBIDDEN_SOURCES: [
    'LEGACY',
    'LOCAL_OVERRIDE',
    'UI_OVERRIDE',
    'ADAPTER_OVERRIDE',
    'REPORT_OVERRIDE'
  ],
  PROTOCOL_VERSION: 'ELSA-2.0',
  CONSTITUTIONAL_VERSION: 'SCCF-1.0'
};
