import React from 'react';
import { EnrichedArtifact } from '../../read-model/ArchitectureExplorerModel';

interface Props {
  artifact: EnrichedArtifact;
}

export const EvidenceViewer: React.FC<Props> = ({ artifact }) => {
  return (
    <div className="bg-[#121214] border border-[#2a2a2f] rounded-lg p-6 text-white h-full overflow-y-auto">
      <h3 className="text-xl font-semibold mb-4">Evidence Journal</h3>
      <p className="text-sm text-white/60 mb-6 border-b border-[#2a2a2f] pb-4">
        Traceability for: <span className="text-white font-medium">{artifact.name}</span>
      </p>

      <div className="space-y-4">
        {artifact.inboundRelationships.length > 0 && (
          <div>
            <h4 className="text-xs text-white/40 uppercase tracking-wide mb-2">Inbound References</h4>
            <div className="space-y-1">
              {artifact.inboundRelationships.map((r, i) => (
                <div key={i} className="text-sm bg-[#1a1a1f] px-3 py-2 rounded border border-[#2a2a2f]">
                  <span className="text-[#808085]">{r.type}</span> from source <span className="font-mono text-xs">{r.sourceId.substring(0, 8)}</span>
                  <div className="text-xs text-white/30 mt-1">Method: {r.discoveryMethod} | Conf: {r.confidence}</div>
                </div>
              ))}
            </div>
          </div>
        )}

        {artifact.outboundRelationships.length > 0 && (
          <div>
            <h4 className="text-xs text-white/40 uppercase tracking-wide mb-2 mt-4">Outbound References</h4>
            <div className="space-y-1">
              {artifact.outboundRelationships.map((r, i) => (
                <div key={i} className="text-sm bg-[#1a1a1f] px-3 py-2 rounded border border-[#2a2a2f]">
                  <span className="text-[#808085]">{r.type}</span> to target <span className="font-mono text-xs">{r.targetId.substring(0, 8)}</span>
                  <div className="text-xs text-white/30 mt-1">Method: {r.discoveryMethod} | Conf: {r.confidence}</div>
                </div>
              ))}
            </div>
          </div>
        )}

        {artifact.observations.map(obs => (
          <div key={obs.id} className="mt-4 bg-[#1a1a1f] p-3 border-l-2 border-[#4f4f5a] rounded">
            <h4 className="text-sm font-medium">Fact Observed: {obs.metric}</h4>
            <p className="text-xs text-white/50 mt-1">Snapshot Source: {obs.sourceSnapshot.id}</p>
            <p className="text-xs text-white/50">Generated By: {obs.generatedBy}</p>
          </div>
        ))}
      </div>
    </div>
  );
};
