BEGIN;
ALTER TABLE tenant.tenants ADD COLUMN IF NOT EXISTS legacy_id VARCHAR(255) UNIQUE;
ALTER TABLE tenant.tenants ADD COLUMN IF NOT EXISTS legacy_source VARCHAR(50) DEFAULT 'FIRESTORE';
ALTER TABLE tenant.companies ADD COLUMN IF NOT EXISTS legacy_id VARCHAR(255) UNIQUE;
ALTER TABLE tenant.companies ADD COLUMN IF NOT EXISTS legacy_source VARCHAR(50) DEFAULT 'FIRESTORE';
COMMIT;
