export const CAPABILITIES = {
  // Financial Module
  FINANCIAL_DASHBOARD_VIEW: 'FINANCIAL.DASHBOARD.VIEW',
  FINANCIAL_ENTRIES_VIEW: 'FINANCIAL.ENTRIES.VIEW',
  FINANCIAL_ENTRIES_IMPORT: 'FINANCIAL.ENTRIES.IMPORT',
  FINANCIAL_BUDGET_MANAGE: 'FINANCIAL.BUDGET.MANAGE',
  
  // Board / Governance
  BOARD_PACK_VIEW: 'BOARD.PACK.VIEW',
  BOARD_DECISION_APPROVE: 'BOARD.DECISION.APPROVE',
  
  // Simulations
  SIMULATION_CREATE: 'SIMULATION.CREATE',
  SIMULATION_VIEW: 'SIMULATION.VIEW',
  
  // Tenant & Identity Admin
  TENANT_MANAGE: 'TENANT.MANAGE',
  USER_MANAGE: 'USER.MANAGE',
  
  // System Admin
  SYSTEM_OBSERVABILITY_VIEW: 'SYSTEM.OBSERVABILITY.VIEW',
  SYSTEM_ADMINISTRATION: 'SYSTEM.ADMINISTRATION',
  SYSTEM_INTELLIGENCE_DEBUG: 'SYSTEM.GOVERNANCE.DEBUG',
  
  // Executive Workspace
  EXECUTIVE_WORKSPACE_VIEW: 'EXECUTIVE.WORKSPACE.VIEW',
  EXECUTIVE_WORKSPACE_ACCESS: 'EXECUTIVE.WORKSPACE.ACCESS'
} as const;

export type SystemCapability = typeof CAPABILITIES[keyof typeof CAPABILITIES];
