export enum PartnerType {
  CERTIFIED_ADVISOR = 'CERTIFIED_ADVISOR',
  EXECUTIVE_PARTNER = 'EXECUTIVE_PARTNER'
}

export enum PartnerStatus {
  INVITED = 'INVITED',
  ONBOARDING = 'ONBOARDING',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  TERMINATED = 'TERMINATED'
}

export enum PartnerTier {
  CERTIFIED = 'CERTIFIED',
  PREMIUM = 'PREMIUM',
  STRATEGIC = 'STRATEGIC'
}

export enum PartnerCapability {
  ADVISORY_DELIVERY = 'ADVISORY_DELIVERY',
  CUSTOMER_REFERRAL = 'CUSTOMER_REFERRAL',
  CO_SELLING = 'CO_SELLING',
  IMPLEMENTATION = 'IMPLEMENTATION',
  TRAINING = 'TRAINING'
}
