export type GovernanceModuleDefinition = {
  id: string;
  label: string;
  centralQuestion: string;
  primaryResponsibilities: string[];
  secondaryResponsibilities: string[];
  prohibitedResponsibilities: string[];
  allowedDependencies: string[];
  prohibitedDependencies: string[];
  accessScope: 'company' | 'admin_master' | 'segmented' | 'restricted';
};

export const GovernanceModules: Record<string, GovernanceModuleDefinition> = {
  executive_monitoring_center: {
    id: 'executive_monitoring_center',
    label: 'Executive Monitoring Center',
    centralQuestion: 'What are the immediate vital signs of the institution across all engines?',
    primaryResponsibilities: ['Monitoramento em tempo real', 'Identificação de sinais de deterioração'],
    secondaryResponsibilities: ['Apresentação consolidada de alertas executivos'],
    prohibitedResponsibilities: ['Configuração de playbooks', 'Detecção aprofundada de riscos técnicos'],
    allowedDependencies: ['Score Engine', 'Master Monitoring Engine'],
    prohibitedDependencies: ['Crisis Playbook Engine', 'Tenant Sandbox'],
    accessScope: 'company',
  },
  governance_maturity_center: {
    id: 'governance_maturity_center',
    label: 'Governance Maturity Center',
    centralQuestion: 'How is the institution evolving in its fundamental governance practices?',
    primaryResponsibilities: ['Avaliação de maturidade', 'Roadmaps evolutivos', 'Definição de princípios'],
    secondaryResponsibilities: ['Acompanhamento de OKRs de governança'],
    prohibitedResponsibilities: ['Validação fiduciária', 'Gestão de acessos SaaS'],
    allowedDependencies: ['Governance Engine', 'Institutional Memory'],
    prohibitedDependencies: ['Real-time Monitoring'],
    accessScope: 'company',
  },
  leadership_dna_center: {
    id: 'leadership_dna_center',
    label: 'Leadership DNA Center',
    centralQuestion: 'Does the leadership possess the necessary competence and ethical alignment for the strategic mandate?',
    primaryResponsibilities: ['Mapeamento de perfis', 'Avaliação de competências', 'Análise de dilemas éticos'],
    secondaryResponsibilities: ['Planos de desenvolvimento focado em liderança'],
    prohibitedResponsibilities: ['Cálculo de folha de pagamento', 'Estruturação societária'],
    allowedDependencies: ['HR Intelligence', 'Causal Logic'],
    prohibitedDependencies: ['Financial Accounting'],
    accessScope: 'company',
  },
  institutional_structure_center: {
    id: 'institutional_structure_center',
    label: 'Institutional Structure Center',
    centralQuestion: 'Is the organizational structure adequately segregated and empowered?',
    primaryResponsibilities: ['Organograma', 'Linhas de autoridade', 'Segregation of Duties (SoD)'],
    secondaryResponsibilities: ['Matrizes de alçada'],
    prohibitedResponsibilities: ['Avaliação de maturidade global'],
    allowedDependencies: ['HR Intelligence', 'Governance Engine'],
    prohibitedDependencies: ['Marketing Engine'],
    accessScope: 'company',
  },
  board_deck_center: {
    id: 'board_deck_center',
    label: 'Board Deck Center',
    centralQuestion: 'Are the deliberative bodies adequately informed with auditable artifacts?',
    primaryResponsibilities: ['Central de relatórios', 'Trilha de documentos', 'Atas e convocações'],
    secondaryResponsibilities: ['Gestão de agendas de conselho'],
    prohibitedResponsibilities: ['Simulação de capital', 'Rastreamento em tempo real'],
    allowedDependencies: ['Reporting Engine', 'Document Storage'],
    prohibitedDependencies: ['Runtime Metrics'],
    accessScope: 'company',
  },
  fiduciary_validation_center: {
    id: 'fiduciary_validation_center',
    label: 'Fiduciary Validation Center',
    centralQuestion: 'Are all actions and relationships transparent and free from hidden conflicts of interest?',
    primaryResponsibilities: ['Gestão de conflitos de interesse', 'Partes relacionadas', 'Legitimidade fiduciária'],
    secondaryResponsibilities: ['Auditoria de vínculos diretores'],
    prohibitedResponsibilities: ['Desenho de organograma'],
    allowedDependencies: ['Governance Engine', 'Compliance Data'],
    prohibitedDependencies: ['Product Entitlements'],
    accessScope: 'company',
  },
  risk_exposure_center: {
    id: 'risk_exposure_center',
    label: 'Risk Exposure Center',
    centralQuestion: 'What systemic or operational threats could compromise institutional continuity?',
    primaryResponsibilities: ['Inteligência de vulnerabilidade', 'Matriz de riscos', 'Mapas de calor de exposição'],
    secondaryResponsibilities: ['Análise de impacto em cenários de estresse'],
    prohibitedResponsibilities: ['Orquestração de resposta a crises'],
    allowedDependencies: ['Risk Engine', 'Stress Test Engine'],
    prohibitedDependencies: ['Leadership Profiling'],
    accessScope: 'company',
  },
  decision_lifecycle_center: {
    id: 'decision_lifecycle_center',
    label: 'Decision Lifecycle Center',
    centralQuestion: 'How are critical decisions proposed, approved, documented, and verified?',
    primaryResponsibilities: ['Rastreabilidade de decisões', 'Workflows de aprovação', 'Accountability'],
    secondaryResponsibilities: ['Logs de assinatura e evidência técnica (Admin)'],
    prohibitedResponsibilities: ['Aprovação de planos SaaS'],
    allowedDependencies: ['Workflow Engine', 'Audit Log', 'Governance Engine'],
    prohibitedDependencies: ['Crisis Execution'],
    accessScope: 'segmented',
  },
  crisis_response_center: {
    id: 'crisis_response_center',
    label: 'Crisis Response Center',
    centralQuestion: 'If a critical threshold is breached, how is the immediate systemic response orchestrated?',
    primaryResponsibilities: ['Orquestração de playbooks', 'Contingência sistêmica', 'Simulação de crises'],
    secondaryResponsibilities: ['Timeline e escalonamento de owners'],
    prohibitedResponsibilities: ['Detecção inicial', 'Matriz de riscos contínua', 'Alertas de negócio preventivos'],
    allowedDependencies: ['Playbook Engine', 'Action Orchestrator'],
    prohibitedDependencies: ['Predictive Inference'],
    accessScope: 'restricted',
  },
  runtime_observability_center: {
    id: 'runtime_observability_center',
    label: 'Runtime Observability Center',
    centralQuestion: 'Is the underlying computational intelligence operating within validated parameters?',
    primaryResponsibilities: ['Saúde computacional', 'Integridade dos motores matemáticos', 'Latência sistêmica'],
    secondaryResponsibilities: ['Tracing de eventos de runtime'],
    prohibitedResponsibilities: ['Métricas financeiras do cliente'],
    allowedDependencies: ['Telemetry Data', 'System Logs'],
    prohibitedDependencies: ['Business Causal Engine'],
    accessScope: 'admin_master',
  },
  product_governance_center: {
    id: 'product_governance_center',
    label: 'Product Governance Center',
    centralQuestion: 'What capabilities is this tenant entitled to consume from the Illumine SaaS platform?',
    primaryResponsibilities: ['Quotas e limites', 'Planos de assinatura', 'Feature flags globais'],
    secondaryResponsibilities: ['Controle de onboarding'],
    prohibitedResponsibilities: ['Auditoria fiduciária'],
    allowedDependencies: ['Entitlement Service', 'Billing Module'],
    prohibitedDependencies: ['Risk Heatmaps'],
    accessScope: 'admin_master',
  },
  multi_tenant_governance_center: {
    id: 'multi_tenant_governance_center',
    label: 'Multi-Tenant Governance Center',
    centralQuestion: 'Are all cross-tenant boundaries, data isolations, and access policies strictly enforced?',
    primaryResponsibilities: ['Segurança e isolamento', 'Auditoria cross-tenant', 'Data sovereignty'],
    secondaryResponsibilities: ['Gestão de acessos mestres'],
    prohibitedResponsibilities: ['Gestão de usuários da empresa local'],
    allowedDependencies: ['IAM Engine', 'Isolation Protocols'],
    prohibitedDependencies: ['Company Strategy Planning'],
    accessScope: 'admin_master',
  },
};
